server.port=8443

spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# JSON
spring.jackson.mapper.default-view-inclusion=true

# Perfil por defecto (se sobrescribe con variable de entorno SPRING_PROFILES_ACTIVE)
# spring.profiles.active=dev

# Permitir referencias circulares
spring.main.allow-circular-references=true

app.contact.email=${CONTACT_EMAIL:admin@tudominio.com}