server.port=8888

spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# JSON
spring.jackson.mapper.default-view-inclusion=true

# Perfil por defecto
spring.profiles.active=dev

# Permitir referencias circulares
spring.main.allow-circular-references=true
