apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-server
  namespace: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-server
  template:
    metadata:
      labels:
        app: oauth2-server
    spec:
      containers:
        - name: oauth2-server
          image: felixmurcia/oauth2server:v20260224-2009
          
          command: ["java"]
          args: ["-jar", "/app/app.jar", "--spring.profiles.active=prod"]

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod

            - name: JWT_SIGNING_KEY
              valueFrom:
                secretKeyRef:
                  name: oauth2-secrets
                  key: jwt-signing-key

            - name: JWT_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: oauth2-secrets
                  key: oauth-audience

            - name: OAUTH_REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  name: oauth2-secrets
                  key: oauth-redirect-uri

            - name: DEFAULT_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: oauth2-secrets
                  key: default-admin-username

            - name: DEFAULT_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oauth2-secrets
                  key: default-admin-password

            - name: DEFAULT_USER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: oauth2-secrets
                  key: default-user-username

            - name: DEFAULT_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oauth2-secrets
                  key: default-user-password

            - name: ISSUER_URL
              valueFrom:
                secretKeyRef:
                  name: oauth2-secrets
                  key: issuer-url

            - name: H2_USERNAME
              valueFrom:
                secretKeyRef:
                  name: oauth2-secrets
                  key: h2-username

            - name: H2_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oauth2-secrets
                  key: h2-password

            - name: CINE_PLATFORM_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth2-secrets
                  key: CINE_PLATFORM_SECRET

            - name: CINE_PLATFORM_REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  name: oauth2-secrets
                  key: CINE_PLATFORM_REDIRECT_URI

            - name: TRANSCRIBEAPP_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth2-secrets
                  key: TRANSCRIBEAPP_SECRET

            - name: TRANSCRIBEAPP_REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  name: oauth2-secrets
                  key: TRANSCRIBEAPP_REDIRECT_URI

            - name: SERVER_PORT
              value: "8443"
            - name: SERVER_SSL_ENABLED
              value: "true"
            - name: SERVER_SSL_KEY_STORE
              value: "/certs/keystore.p12"
            - name: SERVER_SSL_KEY_STORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tls-keystore
                  key: keystore-password

          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8443
              name: https
              hostPort: 30444

          volumeMounts:
            - name: oauth2-data
              mountPath: /data
            - name: tls-certs
              mountPath: /certs
              readOnly: true

      volumes:
        - name: oauth2-data
          persistentVolumeClaim:
            claimName: oauth2-pvc
        - name: tls-certs
          secret:
            secretName: tls-keystore