apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-server
  namespace: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-server
  template:
    metadata:
      labels:
        app: oauth2-server
    spec:
      containers:
        - name: oauth2-server
          image: felixmurcia/oauth2server:v20260223-1533
          
          # Ejecuta tu script de producción dentro del contenedor
          command: ["/bin/sh", "-c", "/app/run-prod.sh"]

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod

            - name: JWT_SIGNING_KEY
              valueFrom:
                secretKeyRef:
                  name: oauth2-secrets
                  key: jwt-signing-key

            - name: JWT_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: oauth2-secrets
                  key: oauth-audience

            - name: OAUTH_REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  name: oauth2-secrets
                  key: oauth-redirect-uri

            - name: DEFAULT_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: oauth2-secrets
                  key: default-admin-username

            - name: DEFAULT_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oauth2-secrets
                  key: default-admin-password

            - name: DEFAULT_USER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: oauth2-secrets
                  key: default-user-username

            - name: DEFAULT_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oauth2-secrets
                  key: default-user-password

            - name: ISSUER_URL
              valueFrom:
                secretKeyRef:
                  name: oauth2-secrets
                  key: issuer-url

            - name: H2_USERNAME
              valueFrom:
                secretKeyRef:
                  name: oauth2-secrets
                  key: h2-username

            - name: H2_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oauth2-secrets
                  key: h2-password

            - name: CINE_PLATFORM_SECRET
              valueFrom:
                secretKeyRef:
                  name: cine-secret
                  key: CINE_PLATFORM_SECRET

            - name: CINE_PLATFORM_REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  name: cine-secret
                  key: CINE_PLATFORM_REDIRECT_URI
				  
            - name: TRANSCRIBEAPP_SECRET
              valueFrom:
                secretKeyRef:
                  name: cine-secret
                  key: TRANSCRIBEAPP_SECRET

            - name: TRANSCRIBEAPP_REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  name: cine-secret
                  key: TRANSCRIBEAPP_REDIRECT_URI	

          ports:
            - containerPort: 8080
              hostPort: 30444

          volumeMounts:
            - name: oauth2-data
              mountPath: /data

      volumes:
        - name: oauth2-data
          persistentVolumeClaim:
            claimName: oauth2-pvc
