apiVersion: v1
kind: Service
metadata:
  name: oauth2-server
  namespace: auth
spec:
  selector:
    app: oauth2-server
  ports:
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
    - name: https-nodeport
      port: 8443
      targetPort: 8443
      nodePort: 30444
      protocol: TCP
  type: NodePort